# VARS
THREADS="32"
AVERAGE="32"
MARCH="native"
PRIORITY="5"
NTHREADS="32"
OPTLEVEL="3"
SAFE_FAST_MATH="-fno-math-errno -fno-trapping-math"
AGGRESSIVE="${SAFE_FAST_MATH} -flto=auto -fuse-linker-plugin -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition"

# These warnings indicate likely runtime problems with LTO, so promote them
# to errors. If a package fails to build with these, LTO should not be used there.
WARNING_FLAGS="-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"

# COMPILATION OPTIONS
COMMON_FLAGS="-march=${MARCH} -O${OPTLEVEL} ${WARNING_FLAGS} -pipe ${AGGRESSIVE} -ggdb3"
RUSTFLAGS="-Copt-level=${OPTLEVEL} -Ctarget-cpu=${MARCH} -Ccodegen-units=${THREADS} -Clto=fat -Cembed-bitcode -Zdylib-lto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j${THREADS} -l${AVERAGE}"
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --jobs ${THREADS} --load-average ${AVERAGE} --keep-going --with-bdeps=y --complete-graph=y --verbose"
CMAKE_MAKEFILE_GENERATOR="ninja"

# CUDA
CUDAHOSTCXX="/usr/x86_64-pc-linux-gnu/gcc-bin/12"
CUDA_ARCH="sm_61 sm_86"
CUDA_ARCH_BIN="6.1 8.6"
CUDA_GENERATION="Pascal Ampere"
CUDA_VERBOSE="false"
TORCH_CUDA_ARCH_LIST="6.1;8.6"

# SETTINGS
ACCEPT_LICENSE="*"
FEATURES="parallel-install parallel-fetch splitdebug compressdebug -nostrip installsources"
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"
ABI_X86="32 64"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
CCACHE_DIR="/var/cache/ccache"
INPUT_DEVICES="libinput"
CURL_SSL="openssl"
VIDEO_CARDS="nvidia"
GRUB_PLATFORMS="efi-64"
LUA_SINGLE_TARGET="lua5-4"

# USE FLAGS
UCRYPT="crypt gnupg gpg"
USYS="grub dist-kernel"
UEXTRA="cups xinerama scanner usb scanner v4l"
UCONN="wifi bluetooth zeroconf networkmanager avahi"
UCOMPRESSION="bzip2 zlib zstd gzip lzo lzma modules-compress"
UOPTIMIZE="custom-cflags openmp boost graphite threads asm xs pgo pch lto jit optimization strong-optimization orc -cpudetection native-extensions -sysprof -pie -pic -unwind -ssp -hardened -sanitize -debug"
UGFX="gif jpeg png svg webp tiff xft lcms xml postscript truetype X qt6 gles2 appindicator libnotify fontconfig opencl"
UNVIDIA="nvidia vdpau nvenc vulkan opengl cuda"
UDEVEL="git emacs -debug -doc man valgrind unwind"
UMISC="ncurses unicode dbus udev alsa games"
USOUND="pulseaudio pipewire sound-server gstreamer"
UCOMP="bash-completion zsh-completion fish-completion"
USYSTEM = "native-symlinks system-mesa system-libyaml system-lua system-bootstrap system-llvm system-lz4 system-sqlite system-ffmpeg system-icu system-av1 system-harfbuzz system-jpeg system-libevent system-librnp system-libvpx system-png system-python-libs system-webp system-ssl system-zlib system-boost"
USE="${UCRYPT} ${UCONN} ${UCOMPRESSION} ${UOPTIMIZE} ${UDEVEL} ${USOUND} ${UMISC} ${UCOMP} ${USYS} ${UGFX} ${UNVIDIA} ${USYSTEM} ${UEXTRA}"

# NOTE: This stage was built with the bindist Use flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8
