# VARS
THREADS="32"
AVERAGE="32"
PRIORITY="5"
MARCH="native" # x86-64-v3 is needed for Valgrind and rr but native gives us the best performance.
OPTLEVEL="3"
LTO="-flto=auto -fuse-linker-plugin -fdevirtualize-at-ltrans"

NTHREADS="${THREADS}"

# These warnings indicate likely runtime problems with LTO, so promote them
# to errors. If a package fails to build with these, LTO should not be used there.
WARNING_FLAGS="-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"
DEBUG_FLAGS="${WARNING_FLAGS} -ggdb3"

# MINIMAL OPTIONS for debugging and repairing a broken system.
COMMON_FLAGS_MINIMAL="-march=${MARCH} -O${OPTLEVEL} -pipe"
RUSTFLAGS_MINIMAL="-Copt-level=${OPTLEVEL} -Ctarget-cpu=${MARCH} -Ccodegen-units=${THREADS}"
UOPTIMIZE_MINIMAL="openmp boost graphite threads asm xs pch jit optimization strong-optimization orc -cpudetection native-extensions -sysprof -pie -pic -unwind -ssp -hardened -sanitize -debug"

# COMPILATION OPTIONS
COMMON_FLAGS="${COMMON_FLAGS_MINIMAL} ${DEBUG_FLAGS} ${LTO}"
RUSTFLAGS="${RUSTFLAGS_MINIMAL}"
UOPTIMIZE="${UOPTIMIZE_MINIMAL} custom-cflags lto pgo"

# For repairing a broken system.
#COMMON_FLAGS="${COMMON_FLAGS_MINIMAL}"
#RUSTFLAGS="${RUSTFLAGS_MINIMAL}"
#UOPTIMIZE="${UOPTIMIZE_MINIMAL}"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j${THREADS} -l${AVERAGE}"
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --jobs ${THREADS} --load-average ${AVERAGE} --keep-going --with-bdeps=y --complete-graph=y --verbose"
CMAKE_MAKEFILE_GENERATOR="ninja"

# CUDA
CUDAHOSTCXX="/usr/x86_64-pc-linux-gnu/gcc-bin/12"
NVCC_PREPEND_FLAGS="--compiler-bindir /usr/x86_64-pc-linux-gnu/gcc-bin/12"
CUDA_ARCH="sm_61 sm_86"
CUDA_ARCH_BIN="6.1 8.6"
CUDA_GENERATION="Pascal Ampere"
CUDA_VERBOSE="false"
TORCH_CUDA_ARCH_LIST="6.1;8.6"

# SETTINGS
ACCEPT_LICENSE="*"
FEATURES="parallel-install parallel-fetch splitdebug compressdebug -nostrip installsources"
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"
ABI_X86="32 64"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
CCACHE_DIR="/var/cache/ccache"
INPUT_DEVICES="libinput"
CURL_SSL="openssl"
VIDEO_CARDS="nvidia"
GRUB_PLATFORMS="efi-64"
LUA_SINGLE_TARGET="lua5-4"

# USE FLAGS
UCRYPT="crypt gnupg gpg cryptsetup"
USYS="grub dist-kernel"
UEXTRA="cups xinerama scanner usb scanner v4l"
UCONN="wifi bluetooth zeroconf networkmanager avahi"
UCOMPRESSION="bzip2 zlib zstd gzip lzo lzma compress-zstd"
UGFX="gif jpeg png svg webp tiff xft lcms xml postscript truetype X wayland qt6 gles2 appindicator libnotify fontconfig opencl"
UNVIDIA="nvidia vdpau nvenc vulkan opengl cuda"
UDEVEL="git emacs -debug -doc man valgrind unwind multitarget"
UMISC="ncurses unicode dbus udev alsa games"
USOUND="pulseaudio pipewire sound-server gstreamer"
UCOMP="bash-completion zsh-completion fish-completion"
USYSTEM = "native-symlinks system-mesa system-libyaml system-lua system-bootstrap system-llvm system-lz4 system-sqlite system-ffmpeg system-icu system-av1 system-harfbuzz system-jpeg system-libevent system-librnp system-libvpx system-png system-python-libs system-webp system-ssl system-zlib system-boost"
USE="${UCRYPT} ${UCONN} ${UCOMPRESSION} ${UOPTIMIZE} ${UDEVEL} ${USOUND} ${UMISC} ${UCOMP} ${USYS} ${UGFX} ${UNVIDIA} ${USYSTEM} ${UEXTRA}"

# NOTE: This stage was built with the bindist Use flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8
