#*/* PYTHON_TARGETS: python3_11
x11-drivers/nvidia-drivers -modules-compress

sys-libs/glibc hash-sysv-compat
sys-boot/gnu-efi -custom-cflags # x86_64-pc-linux-gnu-ld: unrecognized option '-Wl,-O1'
games-emulation/retroarch X alsa cdrom dbus egl ffmpeg flac gles2 network opengl opengl_core pulseaudio sdl2 -sdl ssl systemd truetype udev usb v4l vulkan xinerama xrandr xv zlib kms drm osmesa libusb
games-emulation/retroarch-assets ozone
virtual/wine proton staging
app-emulation/wine-staging dos
dev-lang/python tk
net-libs/nodejs npm
sci-mathematics/lean source
x11-base/xorg-server xvfb suid
dev-haskell/* doc hoogle hscolour
net-misc/aria2 bittorrent tcmalloc adns
net-fs/samba -gpg winbind
net-p2p/syncthing tools
dev-util/google-perftools optimisememory largepages
app-editors/emacs harfbuzz tree-sitter json source sqlite webp dynamic-loading imagemagick libxml2 mailutils m17n-lib gui cairo -alsa jit athena Xaw3d -gtk -motif -sound
net-libs/webkit-gtk avif pdf
dev-lang/rust -system-llvm -system-bootstrap clippy
dev-lang/rust-bin rustfmt rust-analyzer rust-src clippy
x11-misc/polybar i3wm curl ipc mpd network
app-alternatives/sh -bash dash
app-emacs/emacs-common gui
media-gfx/imagemagick graphviz heif
app-text/poppler cairo
sys-kernel/gentoo-sources experimental
media-video/ffmpeg opus sdl x264 webp mp3 vorbis
media-sound/mpd flac lame pipe mpg123 opus vorbis zip
media-sound/pulseaudio-daemon -alsa-plugin -udev
media-video/pipewire pipewire-alsa ffmpeg extra echo-cancel
media-libs/libsndfile minimal
media-fonts/iosevka iosevka-aile iosevka-ss05
app-text/enchant -hunspell aspell
www-client/firefox -telemetry hwaccel system-png
sys-apps/kmscon doc pixman
gui-wm/sway grimshot tray wallpapers
sys-kernel/cachyos-sources build symlink
app-text/texlive graphics science luatex xetex context extra pstricks
app-text/texlive-core xetex
app-text/evince djvu cups
dev-debug/gdb source-highlight xxhash xml #debuginfod
sys-devel/binutils pgo
media-video/vlc ogg vorbis
app-arch/p7zip rar
sys-libs/libxcrypt static-libs # for Nix
media-fonts/fonts-meta cjk ms
dev-lang/rust nightly rust-analyzer rustfmt rust-src
www-client/firefox -clang
app-office/libreoffice custom-cflags pdfimport
sys-boot/etcher-bin -system-ffmpeg
app-text/editorconfig-core-c cli
dev-python/python-lsp-server all-plugins
sys-fs/ntfs3g ntfsdecrypt
app-emulation/virt-manager gui
net-misc/curl gopher

#sys-libs/ncurses -gpm
#app-editors/emacs -mailutils -imagemagick
#net-print/cups -zeroconf
#*/* -emacs
#media-video/pipewire -ffmpeg
#net-misc/networkmanager -modemmanager -bluetooth
#gnome-extra/nm-applet -modemmanager -bluetooth

# This is so I can tunnel the sound through the Pulse server without messing
# with the config file.
media-sound/mpd -alsa
