# created by eselect-repo

[src_prepare-overlay]
location = /var/db/repos/src_prepare-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/src_prepare-overlay.git

[nest]
location = /var/db/repos/nest
sync-type = git
sync-uri = https://github.com/gentoo-mirror/nest.git


[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[haskell]
location = /var/db/repos/haskell
sync-type = git
sync-uri = https://github.com/gentoo-mirror/haskell.git

[xwing]
location = /var/db/repos/xwing
sync-type = git
sync-uri = https://github.com/gentoo-mirror/xwing.git

[pentoo]
location = /var/db/repos/pentoo
sync-type = git
sync-uri = https://github.com/gentoo-mirror/pentoo.git


[brother-overlay]
location = /var/db/repos/brother-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/brother-overlay.git

[torbrowser]
location = /var/db/repos/torbrowser
sync-type = git
sync-uri = https://github.com/gentoo-mirror/torbrowser.git

[arrans-overlay]
location = /var/db/repos/arrans-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/arrans-overlay.git

[broverlay]
location = /var/db/repos/broverlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/broverlay.git

[stuff]
location = /var/db/repos/stuff
sync-type = git
sync-uri = https://github.com/gentoo-mirror/stuff.git

[mva]
location = /var/db/repos/mva
sync-type = git
sync-uri = https://github.com/gentoo-mirror/mva.git
