=app-editors/emacs-31.0.9999 **
=app-benchmarks/phoronix-test-suite-9999 **
=dev-lang/ghc-9.8.2 **
=dev-libs/libevent-2.2.1-r2 **

x11-drivers/nvidia-drivers ~amd64
sys-kernel/gentoo-kernel-bin ~amd64
sys-kernel/gentoo-kernel ~amd64
sys-kernel/vanilla-kernel ~amd64
sys-kernel/xanmod-kernel ~amd64
dev-util/wakatime-cli ~amd64
dev-util/github-cli ~amd64
www-client/google-chrome-unstable ~amd64

=dev-python/gymnasium-9999 **
=dev-python/cmakels-9999 **
=dev-python/lsprotocol-9999 **
=dev-ml/ollama-9999 **
=net-misc/mosh-9999 **
=dev-debug/gdb-9999 **
=dev-util/rr-9999 **
=media-sound/easyeffects-9999 **
=x11-misc/dunst-9999 **
=games-emulation/retroarch-9999 **
=games-emulation/retroarch-9999-r4 **

=sys-devel/gcc-15.0.1_pre20250316 **
