# I don't know about Clang's other optimizations like -polly very well.
COMMON_FLAGS="-march=${MARCH} -O${OPTLEVEL} -pipe -flto=thin"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
