# COMMON_FLAGS="-march=native -Ofast fno-finite-math-only -pipe"
RUSTFLAGS="${RUSTFLAGS} -Ctarget-feature=+fast-math"
DISABLE_LTO="-fno-lto -Wno-error=odr -Wno-error=lto-type-mismatch -Wno-error=strict-aliasing"
COMMON_FLAGS="-march=native -Ofast -fno-finite-math-only -pipe ${DISABLE_LTO} -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS} -fpermissive"
# LDFLAGS="-Wl,--as-needed -Wl,-Ofast -Wl,--sort-common ${COMON_FLAGS}"
LDFLAGS="-Wl,--as-needed -Wl,-Ofast -Wl,--sort-common"
LD=/usr/bin/ld.bfd
