RUSTFLAGS="-Copt-level=${OPTLEVEL} -Ctarget-cpu=${MARCH} -Ccodegen-units=${THREADS}"
DISABLE_LTO="-fno-lto -Wno-error=odr -Wno-error=lto-type-mismatch -Wno-error=strict-aliasing"
CFLAGS="${CFLAGS} ${DISABLE_LTO}"
CXXFLAGS="${CXXFLAGS} ${DISABLE_LTO}"
FCFLAGS="${FCFLAGS} ${DISABLE_LTO}"
FFLAGS="${FFLAGS} ${DISABLE_LTO}"
