CFLAGS="${CFLAGS} -Wno-incompatible-pointer-types"
CXXFLAGS="${CXXFLAGS} -Wno-incompatible-pointer-types"
FCFLAGS="${FCFLAGS} -Wno-incompatible-pointer-types"
FFLAGS="${FFLAGS} -Wno-incompatible-pointer-types"
